const lettersContainer = document.getElementById('letters');
const wordsContainer = document.getElementById('words');

// Generate letters A-Z
for(let i = 65; i <= 90; i++) {
    const letter = String.fromCharCode(i);
    const letterDiv = document.createElement('div');
    letterDiv.className = 'letter';
    letterDiv.textContent = letter;
    letterDiv.onclick = () => showWords(letter);
    lettersContainer.appendChild(letterDiv);
}

// Professional dictionary with Hindi meanings
const dictionary = {
    A: [
        { word: "Agenda", meaning: "कार्यसूची" },
        { word: "Allocate", meaning: "आवंटित करना" },
        { word: "Appraisal", meaning: "मूल्यांकन" },
        { word: "Assignment", meaning: "कार्य/असाइनमेंट" },
        { word: "Authorize", meaning: "अधिकार देना" },
        { word: "Amendment", meaning: "संशोधन" },
        { word: "Audit", meaning: "लेखा परीक्षा" },
        { word: "Attachment", meaning: "संलग्नक" },
        { word: "Acquisition", meaning: "अधिग्रहण" },
        { word: "Abstract", meaning: "सारांश" },
        { word: "Adapt", meaning: "अनुकूलित करना" },
        { word: "Analyze", meaning: "विश्लेषण करना" },
        { word: "Assess", meaning: "मूल्यांकन करना" },
        { word: "Approve", meaning: "स्वीकृत करना" },
        { word: "Assign", meaning: "सौंपना" },
        { word: "Align", meaning: "संगत करना" },
        { word: "Articulate", meaning: "स्पष्ट रूप से व्यक्त करना" },
        { word: "Authorize", meaning: "अधिकार देना" },
        { word: "Anticipate", meaning: "पूर्वानुमान करना" },
        { word: "Arrange", meaning: "व्यवस्थित करना" },
        { word: "Appoint", meaning: "नियुक्त करना" },
        { word: "Advance", meaning: "प्रगति करना / अग्रिम देना" },
        { word: "Allocate", meaning: "आवंटित करना" },
        { word: "Approve", meaning: "मंजूरी देना" },
        { word: "Actuate", meaning: "सक्रिय करना" },
        { word: "Adopt", meaning: "अपनाना" },
        { word: "Assess", meaning: "मूल्यांकन करना" },
        { word: "Audit", meaning: "लेखा परीक्षा करना" },
        { word: "Assist", meaning: "सहायता करना" },
        { word: "Authorize", meaning: "अधिकार प्रदान करना" },
        { word: "Align", meaning: "संगत करना" },
        { word: "Acquire", meaning: "अधिग्रहण करना" },
        { word: "Act", meaning: "कार्य करना" },
        { word: "Appraise", meaning: "मूल्यांकन करना" },
        { word: "Arrange", meaning: "व्यवस्थित करना" },
        { word: "Adapt", meaning: "अनुकूलित करना" },
        { word: "Authorize", meaning: "अधिकार प्रदान करना" },
        { word: "Assist", meaning: "सहायता करना" },
        { word: "Advance", meaning: "प्रगति करना / अग्रिम देना" },
        { word: "Anticipate", meaning: "पूर्वानुमान करना" }
    ],
    B: [
        
    { word: "Brief", meaning: "संक्षिप्त विवरण" },
    { word: "Brainstorm", meaning: "विचार-मंथन" },
    { word: "Balance", meaning: "संतुलन" },
    { word: "Board", meaning: "संचालक मंडल" },
    { word: "Brand", meaning: "ब्रांड" },
    { word: "Benefit", meaning: "लाभ" },
    { word: "Business Plan", meaning: "व्यवसाय योजना" },
    { word: "Breakdown", meaning: "विवरण / विश्लेषण" },
    { word: "Backlog", meaning: "अधूरी कार्य सूची" },
    { word: "Briefing", meaning: "संक्षिप्त जानकारी" },
    { word: "Benchmarking", meaning: "मानक निर्धारण" },
    { word: "Breakthrough", meaning: "सफलता / नवीन उपलब्धि" },
    { word: "Boardroom", meaning: "संचालक कक्ष" },
    { word: "Branding Strategy", meaning: "ब्रांड रणनीति" },
    { word: "Balance Sheet", meaning: "बैलेंस शीट" },
    { word: "Business Model", meaning: "व्यवसाय मॉडल" },
    { word: "Bid", meaning: "निविदा / बोली" },
    { word: "Briefcase", meaning: "सूटकेस / कार्यसामग्री ब्रीफकेस" },
    { word: "Bylaw", meaning: "उपबंध / नियम" },
    { word: "Barrier", meaning: "बाधा" },
    { word: "Budgeting", meaning: "बजट बनाना" },
    { word: "Brand Equity", meaning: "ब्रांड मूल्य" },
    { word: "Business Continuity", meaning: "व्यवसाय निरंतरता" },
    { word: "Benefit Analysis", meaning: "लाभ विश्लेषण" },
    { word: "Break-even", meaning: "संतुलन बिंदु" },
    { word: "Briefing Note", meaning: "संक्षिप्त सूचना पत्र" },
    { word: "Benchmark Indicator", meaning: "मानक संकेतक" },
    { word: "Business Intelligence", meaning: "व्यवसायिक जानकारी / बुद्धिमत्ता" }

    ],
    C: [
        
    { word: "Compliance", meaning: "अनुपालन" },
    { word: "Confidential", meaning: "गोपनीय" },
    { word: "Collaboration", meaning: "सहयोग" },
    { word: "Curriculum", meaning: "पाठ्यक्रम" },
    { word: "Capacity", meaning: "क्षमता" },
    { word: "Clause", meaning: "धारा / उपधारा" },
    { word: "Certification", meaning: "प्रमाणपत्र" },
    { word: "Client", meaning: "ग्राहक" },
    { word: "Committee", meaning: "समिति" },
    { word: "Communication", meaning: "संचार" },
    { word: "Coordination", meaning: "समन्वय" },
    { word: "Contribution", meaning: "योगदान" },
    { word: "Calculation", meaning: "गणना" },
    { word: "Costing", meaning: "लागत निर्धारण" },
    { word: "Consultation", meaning: "परामर्श" },
    { word: "Control", meaning: "नियंत्रण" },
    { word: "Confident", meaning: "आत्मविश्वासी" },
    { word: "Clarify", meaning: "स्पष्ट करना" },
    { word: "Concept", meaning: "संकल्पना" },
    { word: "Criteria", meaning: "मापदंड" },
    { word: "Credit", meaning: "ऋण / श्रेय" },
    { word: "Checklist", meaning: "सूची" },
    { word: "Contribution Margin", meaning: "योगदान मार्जिन" },
    { word: "Campaign", meaning: "अभियान" },
    { word: "Creative", meaning: "सृजनात्मक" },
    { word: "Collate", meaning: "संग्रहित करना / मिलाना" },
    { word: "Case Study", meaning: "मामला अध्ययन" },
    { word: "Capability", meaning: "क्षमता" },
    { word: "Conflicts", meaning: "संघर्ष / टकराव" }
    ],
    D: [
        
    { word: "Delegate", meaning: "प्रतिनिधि / सौंपना" },
    { word: "Document", meaning: "दस्तावेज़" },
    { word: "Dashboard", meaning: "डैशबोर्ड" },
    { word: "Distribute", meaning: "वितरित करना" },
    { word: "Data", meaning: "डेटा" },
    { word: "Deliverable", meaning: "प्रदान करने योग्य" },
    { word: "Discussion", meaning: "चर्चा" },
    { word: "Define", meaning: "परिभाषित करना" },
    { word: "Develop", meaning: "विकसित करना" },
    { word: "Decision", meaning: "निर्णय" },
    { word: "Documentation", meaning: "दस्तावेज़ीकरण" },
    { word: "Discipline", meaning: "अनुशासन" },
    { word: "Diversity", meaning: "विविधता" },
    { word: "Design", meaning: "डिज़ाइन / रूपरेखा" },
    { word: "Discussion Point", meaning: "चर्चा बिंदु" },
    { word: "Distribution List", meaning: "वितरण सूची" },
    { word: "Detailing", meaning: "विवरण देना" },
    { word: "Draft", meaning: "मसौदा" },
    { word: "Deployment", meaning: "स्थापना / तैनाती" },
    { word: "Documentation Review", meaning: "दस्तावेज़ समीक्षा" },
    { word: "Deadline Management", meaning: "समाप्ति समय प्रबंधन" },
    { word: "Decision Making", meaning: "निर्णय लेना" },
    { word: "Data Analysis", meaning: "डेटा विश्लेषण" },
    { word: "Department", meaning: "विभाग" },
    { word: "Deliver", meaning: "प्रदान करना" },
    { word: "Discussion Forum", meaning: "चर्चा मंच" },
    { word: "Drafting", meaning: "मसौदा तैयार करना" },
    { word: "Diversify", meaning: "विविधता लाना" },
    { word: "Direct", meaning: "प्रत्यक्ष / निर्देशन करना" },
    { word: "Documentation Standards", meaning: "दस्तावेज़ मानक" },
    { word: "Data Entry", meaning: "डेटा प्रविष्टि" },
    { word: "Drive", meaning: "प्रेरित करना / अभियान" },
    { word: "Define Goals", meaning: "लक्ष्य परिभाषित करना" },
    { word: "Discussion Paper", meaning: "चर्चा पत्र" },
    { word: "Decision Support", meaning: "निर्णय समर्थन" },
    { word: "Daily Report", meaning: "दैनिक रिपोर्ट" },
    { word: "Development Plan", meaning: "विकास योजना" },
    { word: "Due Diligence", meaning: "पर्याप्त परिश्रम" },
    { word: "Documentation System", meaning: "दस्तावेज़ीकरण प्रणाली" }
    ],
    E: [
    
    { word: "Estimate", meaning: "अनुमान" },
    { word: "Evaluate", meaning: "मूल्यांकन करना" },
    { word: "Engage", meaning: "सगाई करना" },
    { word: "Execute", meaning: "निष्पादित करना" },
    { word: "Enhance", meaning: "बढ़ाना" },
    { word: "Empower", meaning: "सशक्त बनाना" },
    { word: "Establish", meaning: "स्थापित करना" },
    { word: "Expertise", meaning: "विशेषज्ञता" },
    { word: "Efficient", meaning: "कुशल" },
    { word: "Eliminate", meaning: "हटाना" },
    { word: "Email", meaning: "ईमेल" },
    { word: "Event", meaning: "कार्यक्रम" },
    { word: "Entry", meaning: "प्रविष्टि" },
    { word: "Equipment", meaning: "उपकरण" },
    { word: "Expenditure", meaning: "खर्च" },
    { word: "Engagement", meaning: "सगाई / भागीदारी" },
    { word: "Emergency", meaning: "आपात स्थिति" },
    { word: "Examine", meaning: "परीक्षण करना" },
    { word: "Evaluation", meaning: "मूल्यांकन" },
    { word: "Expectation", meaning: "उम्मीद" },
    { word: "Entry-Level", meaning: "प्रवेश स्तर" },
    { word: "Experience", meaning: "अनुभव" },
    { word: "Extension", meaning: "विस्तार" },
    { word: "Engross", meaning: "ध्यान केंद्रित करना" },
    { word: "Evidence", meaning: "साक्ष्य" },
    { word: "Encourage", meaning: "प्रोत्साहित करना" },
    { word: "Enterprise", meaning: "उद्यम" },
    { word: "Exchange", meaning: "विनिमय" },
    { word: "Executive", meaning: "कार्यकारी" },
    { word: "Edit", meaning: "संपादित करना" }
    ],
    F: [
    { word: "Follow-up", meaning: "अनुसरण / फॉलो-अप" },
    { word: "Forecast", meaning: "पूर्वानुमान" },
    { word: "Facilitate", meaning: "सुविधा प्रदान करना" },
    { word: "File", meaning: "फ़ाइल / अभिलेख" },
    { word: "Focus", meaning: "केंद्रित करना" },
    { word: "Form", meaning: "प्रपत्र" },
    { word: "Forward", meaning: "आगे बढ़ाना" },
    { word: "Function", meaning: "कार्य / फ़ंक्शन" },
    { word: "Finance", meaning: "वित्त" },
    { word: "Follow", meaning: "अनुसरण करना" },
    { word: "Formulate", meaning: "रूपरेखा तैयार करना" },
    { word: "Fund", meaning: "कोष / निधि" },
    { word: "Facsimile", meaning: "फैक्स / प्रतिलिपि" },
    { word: "Fast-track", meaning: "तेज़ गति से करना" },
    { word: "Feature", meaning: "विशेषता" },
    { word: "Fill", meaning: "भरना" },
    { word: "Flag", meaning: "संकेत देना / चिह्नित करना" },
    { word: "Feedback Loop", meaning: "प्रतिक्रिया चक्र" },
    { word: "File Transfer", meaning: "फ़ाइल स्थानांतरण" },
    { word: "Free", meaning: "मुक्त / खाली" },
    { word: "Frequency", meaning: "आवृत्ति" },
    { word: "Follow-through", meaning: "पूरा करना / पालन करना" },
    { word: "Friendly", meaning: "मैत्रीपूर्ण" },
    { word: "Facilitator", meaning: "सुविधा प्रदाता" },
    { word: "Fix", meaning: "सुलझाना / तय करना" },
    { word: "Framework", meaning: "ढांचा" },
    { word: "Formality", meaning: "औपचारिकता" },
    { word: "Forwarding", meaning: "आगे भेजना" },
    { word: "Filing System", meaning: "फ़ाइलिंग प्रणाली" }

    ],
    G: [
        ,
    { word: "Growth", meaning: "वृद्धि" },
    { word: "Guideline", meaning: "दिशानिर्देश" },
    { word: "Generate", meaning: "उत्पन्न करना" },
    { word: "Governance", meaning: "शासन" },
    { word: "Grant", meaning: "अनुदान" },
    { word: "Group", meaning: "समूह" },
    { word: "Global", meaning: "वैश्विक" },
    { word: "Gather", meaning: "संग्रह करना" },
    { word: "Guarantee", meaning: "गारंटी" },
    { word: "General", meaning: "सामान्य" },
    { word: "Guide", meaning: "मार्गदर्शन करना" },
    { word: "Growth Rate", meaning: "वृद्धि दर" },
    { word: "Grid", meaning: "ग्रिड / जाली" },
    { word: "Graph", meaning: "ग्राफ़" },
    { word: "Grant Proposal", meaning: "अनुदान प्रस्ताव" },
    { word: "Gathering", meaning: "संग्रह / बैठक" },
    { word: "Goal-setting", meaning: "लक्ष्य निर्धारण" },
    { word: "Gross", meaning: "सकल" },
    { word: "Guidance", meaning: "मार्गदर्शन" },
    { word: "Group Meeting", meaning: "समूह बैठक" },
    { word: "Growth Strategy", meaning: "वृद्धि रणनीति" },
    { word: "Govern", meaning: "शासन करना" },
    { word: "General Meeting", meaning: "सामान्य सभा" },
    { word: "Goalkeeper", meaning: "रक्षक / जिम्मेदार" },
    { word: "Guarantee Letter", meaning: "गारंटी पत्र" },
    { word: "Grade", meaning: "ग्रेड / स्तर" },
    { word: "Guideline Document", meaning: "दिशानिर्देश दस्तावेज़" },
    { word: "Gross Margin", meaning: "सकल लाभ मार्जिन" },
    { word: "Groundwork", meaning: "भूमिकायोजना / तैयारी" }
    ],
    H: [
        
    { word: "Highlight", meaning: "मुख्य बिंदु" },
    { word: "Host", meaning: "मेजबान / आयोजन करना" },
    { word: "Huddle", meaning: "संक्षिप्त बैठक" },
    { word: "Harmonize", meaning: "संगत करना" },
    { word: "Helpdesk", meaning: "सहायता डेस्क" },
    { word: "Hold", meaning: "रखना / रोकना" },
    { word: "Hire", meaning: "नियुक्ति करना" },
    { word: "Human Resource", meaning: "मानव संसाधन" },
    { word: "Handbook", meaning: "मैनुअल / पुस्तिका" },
    { word: "Hours", meaning: "घंटे / समय" },
    { word: "Headline", meaning: "शीर्षक" },
    { word: "Heuristic", meaning: "अन्वेषणात्मक / सीखने की विधि" },
    { word: "History", meaning: "इतिहास / पृष्ठभूमि" },
    { word: "Hosting Service", meaning: "होस्टिंग सेवा" },
    { word: "Hierarchy Chart", meaning: "पदक्रम चार्ट" },
    { word: "Hazard", meaning: "जोखिम / खतरा" },
    { word: "Human Capital", meaning: "मानव पूँजी" },
    { word: "Help", meaning: "सहायता" },
    { word: "Headline Report", meaning: "मुख्य रिपोर्ट" },
    { word: "Hold Meeting", meaning: "बैठक आयोजित करना" },
    { word: "Hands-on", meaning: "व्यावहारिक" },
    { word: "Highlight Report", meaning: "मुख्य बिंदु रिपोर्ट" },
    { word: "Home Office", meaning: "घर से कार्यालय" },
    { word: "Hyperlink", meaning: "हाइपरलिंक" },
    { word: "Hub", meaning: "केंद्र / मुख्य स्थल" },
    { word: "Hand-off", meaning: "संपर्क/हस्तांतरण" },
    { word: "Honesty", meaning: "ईमानदारी" },
    { word: "Handle Request", meaning: "अनुरोध को संभालना" }
    ],
    I: [
    
    { word: "Ice", meaning: "बर्फ़" },
    { word: "Idea", meaning: "विचार" },
    { word: "Identify", meaning: "पहचानना" },
    { word: "Idle", meaning: "आलसी / निष्क्रिय" },
    { word: "Ignore", meaning: "नज़रअंदाज़ करना" },
    { word: "Image", meaning: "छवि / तस्वीर" },
    { word: "Imitate", meaning: "अनुकरण करना" },
    { word: "Impact", meaning: "प्रभाव" },
    { word: "Important", meaning: "महत्वपूर्ण" },
    { word: "Impossible", meaning: "असंभव" },
    { word: "Include", meaning: "शामिल करना" },
    { word: "Increase", meaning: "बढ़ाना" },
    { word: "Indicate", meaning: "संकट / संकेत करना" },
    { word: "Individual", meaning: "व्यक्ति" },
    { word: "Industry", meaning: "उद्योग" },
    { word: "Inform", meaning: "सूचित करना" },
    { word: "Inside", meaning: "अंदर" },
    { word: "Inspire", meaning: "प्रेरित करना" },
    { word: "Instant", meaning: "क्षणिक / तुरन्त" },
    { word: "Interest", meaning: "रुचि / ब्याज" },
    { word: "Internet", meaning: "इंटरनेट" },
    { word: "Introduce", meaning: "परिचय देना" },
    { word: "Invest", meaning: "निवेश करना" },
    { word: "Invite", meaning: "आमंत्रित करना" },
    { word: "Iron", meaning: "लोहा / इस्त्री करना" },
    { word: "Island", meaning: "द्वीप" },
    { word: "Issue", meaning: "मुद्दा / समस्या" },
    { word: "Illustrate", meaning: "चित्रित करना" },
    { word: "Imagine", meaning: "कल्पना करना" },
    { word: "Impress", meaning: "प्रभावित करना" },
    { word: "Instantly", meaning: "तुरन्त" },
    { word: "Include", meaning: "शामिल करना" },
    { word: "Improve", meaning: "सुधारना" },
    { word: "Inspect", meaning: "निरीक्षण करना" },
    { word: "Ignore", meaning: "नज़रअंदाज़ करना" },
    { word: "Illness", meaning: "बीमारी" },
    { word: "Inside Out", meaning: "उल्टा-पुल्टा" },
    { word: "Intend", meaning: "इरादा करना" },
    { word: "Item", meaning: "वस्तु / आइटम" },
    { word: "Instantaneous", meaning: "क्षणिक" },
    { word: "Identify With", meaning: "सहमत होना / पहचान बनाना" }
    ],
        J: [
    { word: "Jack", meaning: "जैक / उठाने का उपकरण" },
    { word: "Jam", meaning: "जैम / भीड़" },
    { word: "January", meaning: "जनवरी" },
    { word: "Jaw", meaning: "जुबान / जबड़ा" },
    { word: "Jealous", meaning: "ईर्ष्यालु" },
    { word: "Jeans", meaning: "जीन्स" },
    { word: "Jelly", meaning: "जेली" },
    { word: "Job", meaning: "नौकरी" },
    { word: "Join", meaning: "जोड़ना / सम्मिलित होना" },
    { word: "Joint", meaning: "संयुक्त / जोड़" },
    { word: "Journey", meaning: "यात्रा" },
    { word: "Joy", meaning: "ख़ुशी" },
    { word: "Judge", meaning: "न्यायाधीश / न्याय करना" },
    { word: "Juice", meaning: "रस / जूस" },
    { word: "Jump", meaning: "कूदना" },
    { word: "June", meaning: "जून" },
    { word: "Jungle", meaning: "जंगल" },
    { word: "Junior", meaning: "कनिष्ठ / जूनियर" },
    { word: "Just", meaning: "सिर्फ / न्यायसंगत" },
    { word: "Justice", meaning: "न्याय" },
    { word: "Jacket", meaning: "जैकेट" },
    { word: "Joke", meaning: "मज़ाक" },
    { word: "Joiner", meaning: "जोड़ने वाला / बढ़ई" },
    { word: "Journeying", meaning: "यात्रा करना" },
    { word: "Jumble", meaning: "अव्यवस्था / गड़बड़" },
    { word: "Junction", meaning: "संयोग / चौराहा" },
    { word: "Jewelry", meaning: "आभूषण" },
    { word: "Justify", meaning: "सही ठहराना" },
    { word: "Jostle", meaning: "धक्का देना / धक्का-मुक्की" },
    { word: "Jovial", meaning: "ख़ुशनुमा / हँसमुख" },
    { word: "Juxtapose", meaning: "समीप रखना / तुलना करना" },
    { word: "Jiffy", meaning: "क्षण / बहुत छोटा समय" },
    { word: "Juggle", meaning: "जुगल करना / संतुलित करना" },
    { word: "Jeer", meaning: "मज़ाक उड़ाना" },
    { word: "Jet", meaning: "विमान / जल प्रवाह" },
    { word: "Junction Box", meaning: "संयोग बॉक्स / इलेक्ट्रिकल डिब्बा" },
    { word: "Journal", meaning: "साप्ताहिक / पत्रिका" },
    { word: "Jubilant", meaning: "उत्साही / आनंदित" },
    { word: "Juvenile", meaning: "किशोर / युवराज" },
    { word: "Justness", meaning: "न्यायसंगतता" }
    ],

        K: [
    { word: "Kangaroo", meaning: "कंगारू" },
    { word: "Keep", meaning: "रखना" },
    { word: "Key", meaning: "चाबी / महत्वपूर्ण" },
    { word: "Kick", meaning: "ठोकर मारना" },
    { word: "Kid", meaning: "बच्चा / बच्चा बकरी" },
    { word: "Kind", meaning: "दयालु / प्रकार" },
    { word: "King", meaning: "राजा" },
    { word: "Kitchen", meaning: "रसोईघर" },
    { word: "Kite", meaning: "पतंग" },
    { word: "Knee", meaning: "घुटना" },
    { word: "Knife", meaning: "चाकू" },
    { word: "Knock", meaning: "खटखटाना" },
    { word: "Know", meaning: "जानना" },
    { word: "Knowledge", meaning: "ज्ञान" },
    { word: "Knitting", meaning: "सुई से बुनाई" },
    { word: "Keen", meaning: "उत्सुक / तीव्र" },
    { word: "Kernel", meaning: "बीज / मूल" },
    { word: "Kickoff", meaning: "आरंभ / शुरुआत" },
    { word: "Kindergarten", meaning: "बालवाड़ी" },
    { word: "Kettle", meaning: "बर्तन / केतली" },
    { word: "Knight", meaning: "घुड़सवार योद्धा" },
    { word: "Knapsack", meaning: "थैला / बैग" },
    { word: "Knob", meaning: "सिरा / हैंडल" },
    { word: "Knowledgeable", meaning: "ज्ञानवान" },
    { word: "Kudos", meaning: "शाबाशी / प्रशंसा" },
    { word: "Knuckle", meaning: "हाथ की जोड़ वाली हड्डी" },
    { word: "Kickback", meaning: "लौटाना / रिश्वत" },
    { word: "Knockout", meaning: "पराजय / बेहोश करना" },
    { word: "Keep Up", meaning: "बने रहना / अनुसरण करना" },
    { word: "Keypad", meaning: "कीपैड" },
    { word: "Kingdom", meaning: "राज्य" },
    { word: "Kindly", meaning: "कृपया / दयालुता से" },
    { word: "Kiosk", meaning: "कियोस्क / स्टॉल" },
    { word: "Kiss", meaning: "चुम्बन" },
    { word: "Knock Down", meaning: "गिराना / ध्वस्त करना" },
    { word: "Knot", meaning: "गांठ" },
    { word: "Knowledge Base", meaning: "ज्ञान आधार" },
    { word: "Kick Start", meaning: "शुरुआत करना" },
    { word: "Keynote", meaning: "मुख्य वक्तव्य / विषय" },
    { word: "Keep Away", meaning: "दूर रखना" }
    ],
    L: [
        { word: "Label", meaning: "लेबल / चिन्ह" },
    { word: "Labor", meaning: "श्रम / काम" },
    { word: "Ladder", meaning: "सीढ़ी" },
    { word: "Lake", meaning: "झील" },
    { word: "Lamp", meaning: "दीपक / लालटेन" },
    { word: "Land", meaning: "भूमि / उतरना" },
    { word: "Language", meaning: "भाषा" },
    { word: "Large", meaning: "बड़ा" },
    { word: "Last", meaning: "अंतिम / टिकना" },
    { word: "Late", meaning: "देर / विलंबित" },
    { word: "Laugh", meaning: "हँसना" },
    { word: "Launch", meaning: "प्रक्षेपण / शुरू करना" },
    { word: "Law", meaning: "क़ानून" },
    { word: "Layer", meaning: "परत" },
    { word: "Lead", meaning: "नेतृत्व करना / मुख्य" },
    { word: "Leaf", meaning: "पत्ता" },
    { word: "Learn", meaning: "सीखना" },
    { word: "Leave", meaning: "छुट्टी / छोड़ना" },
    { word: "Lecture", meaning: "व्याख्यान" },
    { word: "Leg", meaning: "टांग" },
    { word: "Length", meaning: "लंबाई" },
    { word: "Lesson", meaning: "पाठ / शिक्षा" },
    { word: "Let", meaning: "अनुमति देना" },
    { word: "Letter", meaning: "पत्र / अक्षर" },
    { word: "Level", meaning: "स्तर / स्तरित करना" },
    { word: "Library", meaning: "पुस्तकालय" },
    { word: "Light", meaning: "प्रकाश / हल्का" },
    { word: "Like", meaning: "पसंद करना / समान" },
    { word: "Limit", meaning: "सीमा" },
    { word: "Line", meaning: "लाइन / रेखा" },
    { word: "Link", meaning: "संपर्क / लिंक" },
    { word: "List", meaning: "सूची" },
    { word: "Listen", meaning: "सुनना" },
    { word: "Live", meaning: "जीवित / रहना" },
    { word: "Loan", meaning: "ऋण" },
    { word: "Local", meaning: "स्थानीय" },
    { word: "Location", meaning: "स्थान" },
    { word: "Lock", meaning: "ताला / बंद करना" },
    { word: "Long", meaning: "लंबा" },
    { word: "Look", meaning: "देखना / नजर" },
    { word: "Lose", meaning: "खोना" },
    { word: "Love", meaning: "प्यार" }
    ],
    M: [
        { word: "Machine", meaning: "मशीन" },
    { word: "Magazine", meaning: "मैगज़ीन / पत्रिका" },
    { word: "Mail", meaning: "डाक / मेल" },
    { word: "Main", meaning: "मुख्य" },
    { word: "Maintain", meaning: "बनाए रखना / रखरखाव करना" },
    { word: "Major", meaning: "मुख्य / प्रमुख" },
    { word: "Make", meaning: "बनाना / निर्माण करना" },
    { word: "Manage", meaning: "प्रबंधित करना" },
    { word: "Manual", meaning: "हाथ से / पुस्तिका" },
    { word: "Market", meaning: "बाज़ार" },
    { word: "Marriage", meaning: "विवाह" },
    { word: "Material", meaning: "सामग्री" },
    { word: "Matter", meaning: "मामला / पदार्थ" },
    { word: "Measure", meaning: "माप / मापना" },
    { word: "Media", meaning: "मीडिया / माध्यम" },
    { word: "Medical", meaning: "चिकित्सकीय" },
    { word: "Meeting", meaning: "बैठक" },
    { word: "Memory", meaning: "स्मृति / याद" },
    { word: "Mention", meaning: "उल्लेख करना" },
    { word: "Message", meaning: "संदेश" },
    { word: "Method", meaning: "विधि / तरीका" },
    { word: "Middle", meaning: "मध्य / बीच" },
    { word: "Mind", meaning: "मन / ध्यान देना" },
    { word: "Minimum", meaning: "न्यूनतम" },
    { word: "Minute", meaning: "क्षण / मिनट" },
    { word: "Mirror", meaning: "दर्पण" },
    { word: "Miss", meaning: "छोड़ना / मिस करना" },
    { word: "Mission", meaning: "मिशन / उद्देश्य" },
    { word: "Model", meaning: "मॉडल / नमूना" },
    { word: "Modern", meaning: "आधुनिक" },
    { word: "Moment", meaning: "क्षण / समय" },
    { word: "Money", meaning: "पैसा" },
    { word: "Month", meaning: "महीना" },
    { word: "Mood", meaning: "मनोस्थिति / मूड" },
    { word: "Moon", meaning: "चाँद" },
    { word: "Morning", meaning: "सुबह" },
    { word: "Motion", meaning: "गतिशीलता / गति" },
    { word: "Move", meaning: "चलाना / स्थानांतरित करना" },
    { word: "Movie", meaning: "फ़िल्म" },
    { word: "Music", meaning: "संगीत" },
    { word: "Must", meaning: "ज़रूरी / आवश्यक" }
    ],
    N: [
    { word: "Name", meaning: "नाम" },
    { word: "Nation", meaning: "राष्ट्र" },
    { word: "Natural", meaning: "प्राकृतिक" },
    { word: "Nature", meaning: "प्रकृति" },
    { word: "Near", meaning: "पास / निकट" },
    { word: "Necessary", meaning: "आवश्यक" },
    { word: "Need", meaning: "ज़रूरत / आवश्यकता" },
    { word: "Neighbor", meaning: "पड़ोसी" },
    { word: "Network", meaning: "नेटवर्क / जाल" },
    { word: "News", meaning: "समाचार" },
    { word: "Next", meaning: "अगला" },
    { word: "Nice", meaning: "अच्छा / सुंदर" },
    { word: "Night", meaning: "रात" },
    { word: "No", meaning: "नहीं" },
    { word: "Noise", meaning: "शोर" },
    { word: "Normal", meaning: "सामान्य" },
    { word: "North", meaning: "उत्तर" },
    { word: "Note", meaning: "नोट / लेख" },
    { word: "Nothing", meaning: "कुछ नहीं" },
    { word: "Notice", meaning: "सूचना / नोटिस" },
    { word: "Now", meaning: "अब" },
    { word: "Number", meaning: "संख्या" },
    { word: "Nurse", meaning: "नर्स" },
    { word: "Narrow", meaning: "संकीर्ण / तंग" },
    { word: "Nameplate", meaning: "नामपट्ट" },
    { word: "Narrative", meaning: "कथा / विवरण" },
    { word: "Navigate", meaning: "मार्गदर्शन करना" },
    { word: "Negotiation", meaning: "वार्ता / समझौता" },
    { word: "Neighboring", meaning: "समीपवर्ती" },
    { word: "Nonsense", meaning: "बकवास" },
    { word: "Noticeable", meaning: "सुस्पष्ट / दिखने योग्य" },
    { word: "Nurture", meaning: "पालन-पोषण करना" },
    { word: "Novel", meaning: "उपन्यास / नया" },
    { word: "Numerical", meaning: "सांख्यिकीय" },
    { word: "Nutrition", meaning: "पोषण" },
    { word: "Neutral", meaning: "तटस्थ" },
    { word: "Necessary Item", meaning: "ज़रूरी वस्तु" },
    { word: "Nightfall", meaning: "सांझ / रात का समय" },
    { word: "Nicely", meaning: "अच्छी तरह" },
    { word: "Notable", meaning: "उल्लेखनीय" },
    { word: "Noticeboard", meaning: "सूचनापट्ट" },
    { word: "Nimble", meaning: "फुर्तीला / चपल" }
],

    O: [
    { word: "Object", meaning: "वस्तु / उद्देश्य" },
    { word: "Observe", meaning: "निरीक्षण करना" },
    { word: "Obvious", meaning: "स्पष्ट" },
    { word: "Occasion", meaning: "अवसर" },
    { word: "Offer", meaning: "प्रस्ताव / देना" },
    { word: "Office", meaning: "कार्यालय" },
    { word: "Official", meaning: "अधिकारी / आधिकारिक" },
    { word: "Often", meaning: "अक्सर" },
    { word: "Old", meaning: "पुराना" },
    { word: "Open", meaning: "खुला / खोलना" },
    { word: "Operate", meaning: "संचालित करना" },
    { word: "Opinion", meaning: "राय" },
    { word: "Opportunity", meaning: "अवसर" },
    { word: "Order", meaning: "आदेश / क्रम" },
    { word: "Organize", meaning: "व्यवस्थित करना" },
    { word: "Original", meaning: "मूल / असली" },
    { word: "Other", meaning: "अन्य" },
    { word: "Otherwise", meaning: "अन्यथा" },
    { word: "Outdoor", meaning: "बाहरी" },
    { word: "Outline", meaning: "रूपरेखा / सार" },
    { word: "Outstanding", meaning: "उल्लेखनीय / उत्कृष्ट" },
    { word: "Owner", meaning: "मालिक" },
    { word: "Output", meaning: "उत्पादन / परिणाम" },
    { word: "Overcome", meaning: "पार पाना / जीतना" },
    { word: "Oversee", meaning: "निरीक्षण करना" },
    { word: "Overtake", meaning: "पार करना / आगे निकल जाना" },
    { word: "Overflow", meaning: "अतिप्रवाह / भर जाना" },
    { word: "Overlook", meaning: "नज़रअंदाज़ करना / देखना" },
    { word: "Observe Carefully", meaning: "ध्यानपूर्वक निरीक्षण करना" },
    { word: "Offer Help", meaning: "सहायता देना" },
    { word: "Onion", meaning: "प्याज़" },
    { word: "Orange", meaning: "संतरा" },
    { word: "Oxygen", meaning: "ऑक्सीजन" },
    { word: "Orderly", meaning: "व्यवस्थित / अनुशासित" },
    { word: "Operate Machine", meaning: "मशीन चलाना" },
    { word: "Official Document", meaning: "अधिकारिक दस्तावेज़" },
    { word: "Open Door", meaning: "खुला दरवाज़ा" },
    { word: "Outdoor Activity", meaning: "बाहरी गतिविधि" },
    { word: "Offer Service", meaning: "सेवा प्रदान करना" },
    { word: "Online", meaning: "ऑनलाइन" },
    { word: "Option", meaning: "विकल्प" },
    { word: "Outcome", meaning: "परिणाम" },
    { word: "Owner’s Manual", meaning: "मालिक की पुस्तिका" }
],
P: [
    { word: "Package", meaning: "पैकेज / पैकेजिंग" },
    { word: "Page", meaning: "पृष्ठ" },
    { word: "Paint", meaning: "रंग / रंगना" },
    { word: "Paper", meaning: "कागज़" },
    { word: "Parent", meaning: "अभिभावक / माता-पिता" },
    { word: "Part", meaning: "भाग / हिस्सा" },
    { word: "Party", meaning: "पार्टी / समूह" },
    { word: "Pass", meaning: "पास / पार करना" },
    { word: "Past", meaning: "अतीत / पहले का" },
    { word: "Pay", meaning: "भुगतान करना" },
    { word: "Peace", meaning: "शांति" },
    { word: "Pen", meaning: "कलम" },
    { word: "People", meaning: "लोग" },
    { word: "Perfect", meaning: "पूर्ण / उत्तम" },
    { word: "Perform", meaning: "प्रदर्शन करना / करना" },
    { word: "Period", meaning: "अवधि / समय" },
    { word: "Permission", meaning: "अनुमति" },
    { word: "Person", meaning: "व्यक्ति" },
    { word: "Phone", meaning: "फोन" },
    { word: "Photo", meaning: "तस्वीर / फोटो" },
    { word: "Place", meaning: "स्थान / जगह" },
    { word: "Plan", meaning: "योजना / योजना बनाना" },
    { word: "Plant", meaning: "पौधा / संयंत्र" },
    { word: "Play", meaning: "खेलना / नाटक" },
    { word: "Please", meaning: "कृपया / प्रसन्न करना" },
    { word: "Point", meaning: "बिंदु / इशारा करना" },
    { word: "Police", meaning: "पुलिस" },
    { word: "Policy", meaning: "नीति" },
    { word: "Popular", meaning: "लोकप्रिय" },
    { word: "Position", meaning: "स्थिति / पद" },
    { word: "Possible", meaning: "संभव" },
    { word: "Post", meaning: "पोस्ट / पत्र" },
    { word: "Power", meaning: "शक्ति / पावर" },
    { word: "Practice", meaning: "अभ्यास / प्रैक्टिस" },
    { word: "Prepare", meaning: "तैयार करना" },
    { word: "Present", meaning: "वर्तमान / प्रस्तुत करना" },
    { word: "Press", meaning: "दबाना / प्रेस" },
    { word: "Price", meaning: "मूल्य / कीमत" },
    { word: "Private", meaning: "निजी / निजी व्यक्ति" },
    { word: "Problem", meaning: "समस्या" },
    { word: "Product", meaning: "उत्पाद" },
    { word: "Project", meaning: "परियोजना / प्रोजेक्ट" },
    { word: "Promise", meaning: "वादा" }
],
Q: [
    { word: "Qualification", meaning: "योग्यता" },
    { word: "Quality", meaning: "गुणवत्ता" },
    { word: "Quantity", meaning: "मात्रा" },
    { word: "Quarter", meaning: "त्रैमासिक / चौथाई" },
    { word: "Question", meaning: "प्रश्न" },
    { word: "Quick", meaning: "तेज़ / जल्दी" },
    { word: "Quiet", meaning: "शांत" },
    { word: "Quit", meaning: "छोड़ना / त्यागना" },
    { word: "Quiz", meaning: "क्विज़ / परीक्षण" },
    { word: "Queue", meaning: "कतार" },
    { word: "Quote", meaning: "उद्धरण / कोटेशन" },
    { word: "Quest", meaning: "अन्वेषण / खोज" },
    { word: "Quench", meaning: "बुझाना / शांत करना" },
    { word: "Questionnaire", meaning: "प्रश्नावली" },
    { word: "Quickly", meaning: "तेज़ी से" },
    { word: "Quaint", meaning: "पुराना और आकर्षक" },
    { word: "Quarrel", meaning: "झगड़ा / विवाद" },
    { word: "Quota", meaning: "कोटा / निर्धारित संख्या" },
    { word: "Quotient", meaning: "भागफल" },
    { word: "Quality Control", meaning: "गुणवत्ता नियंत्रण" },
    { word: "Qualified", meaning: "योग्य" },
    { word: "Quip", meaning: "चुटकुला / मजाक" },
    { word: "Quick Response", meaning: "तेज़ प्रतिक्रिया" },
    { word: "Questioning", meaning: "पूछताछ / जाँच" },
    { word: "Quotable", meaning: "उद्धरण योग्य" },
    { word: "Quell", meaning: "दमन करना / शांत करना" },
    { word: "Quicksand", meaning: "धंसती मिट्टी" },
    { word: "Questing", meaning: "खोज करना" },
    { word: "Quarantine", meaning: "क्वारंटीन / पृथक" },
    { word: "Quibble", meaning: "तर्क में उलझना / विवाद" },
    { word: "Questionable", meaning: "संदेहास्पद" },
    { word: "Quintessential", meaning: "सारगर्भित / आदर्श" },
    { word: "Queue Up", meaning: "कतार में लगना" },
    { word: "Quietly", meaning: "शांतिपूर्वक" },
    { word: "Quick-witted", meaning: "चतुर / तेज-तर्रार" },
    { word: "Quench Thirst", meaning: "प्यास बुझाना" },
    { word: "Quality Assurance", meaning: "गुणवत्ता आश्वासन" },
    { word: "Quorum", meaning: "संचालन योग्य संख्या" },
    { word: "Quadrant", meaning: "चतुर्भुज / खंड" },
    { word: "Quotidian", meaning: "दैनिक / रोज़मर्रा" }
],
R: [
    { word: "Race", meaning: "दौड़ / जाति" },
    { word: "Radio", meaning: "रेडियो" },
    { word: "Rain", meaning: "बारिश" },
    { word: "Raise", meaning: "उठाना / बढ़ाना" },
    { word: "Random", meaning: "यादृच्छिक / बेतरतीब" },
    { word: "Range", meaning: "सीमा / श्रेणी" },
    { word: "Rate", meaning: "दर / मूल्य" },
    { word: "Reach", meaning: "पहुँचना / पहुँच" },
    { word: "Read", meaning: "पढ़ना" },
    { word: "Ready", meaning: "तैयार" },
    { word: "Real", meaning: "वास्तविक / असली" },
    { word: "Reason", meaning: "कारण / तर्क" },
    { word: "Receive", meaning: "प्राप्त करना" },
    { word: "Recent", meaning: "हाल का" },
    { word: "Record", meaning: "रिकॉर्ड / अभिलेख" },
    { word: "Recover", meaning: "सुधारना / ठीक करना" },
    { word: "Red", meaning: "लाल" },
    { word: "Reduce", meaning: "घटाना" },
    { word: "Refer", meaning: "संदर्भित करना / देखना" },
    { word: "Reflect", meaning: "प्रतिबिंबित करना" },
    { word: "Refresh", meaning: "ताज़ा करना" },
    { word: "Refuse", meaning: "इंकार करना / अस्वीकार करना" },
    { word: "Regret", meaning: "अफसोस / खेद" },
    { word: "Relation", meaning: "संबंध" },
    { word: "Relax", meaning: "आराम करना" },
    { word: "Release", meaning: "रिलीज़ / मुक्त करना" },
    { word: "Remember", meaning: "याद रखना" },
    { word: "Remove", meaning: "हटाना" },
    { word: "Repeat", meaning: "दोहराना" },
    { word: "Replace", meaning: "प्रतिस्थापित करना" },
    { word: "Reply", meaning: "जवाब / उत्तर देना" },
    { word: "Report", meaning: "रिपोर्ट / सूचना देना" },
    { word: "Request", meaning: "अनुरोध / मांग" },
    { word: "Require", meaning: "आवश्यक होना" },
    { word: "Research", meaning: "अनुसंधान" },
    { word: "Respect", meaning: "सम्मान / आदर" },
    { word: "Rest", meaning: "आराम / शेष" },
    { word: "Result", meaning: "परिणाम" },
    { word: "Return", meaning: "वापसी / लौटाना" },
    { word: "Rich", meaning: "अमीर / संपन्न" },
    { word: "Ride", meaning: "सवारी करना" }
],
S: [
    { word: "Safe", meaning: "सुरक्षित" },
    { word: "Sail", meaning: "जहाज़ चलाना / पाल" },
    { word: "Salt", meaning: "नमक" },
    { word: "Same", meaning: "समान" },
    { word: "Sand", meaning: "रेत" },
    { word: "Save", meaning: "बचाना / सेव करना" },
    { word: "Say", meaning: "कहना" },
    { word: "School", meaning: "स्कूल" },
    { word: "Science", meaning: "विज्ञान" },
    { word: "Score", meaning: "स्कोर / अंक" },
    { word: "Sea", meaning: "समुद्र" },
    { word: "Search", meaning: "खोज / ढूँढना" },
    { word: "Season", meaning: "मौसम / अवधि" },
    { word: "Seat", meaning: "सीट / बैठना" },
    { word: "Second", meaning: "दूसरा / सेकंड" },
    { word: "See", meaning: "देखना" },
    { word: "Sell", meaning: "बेचना" },
    { word: "Send", meaning: "भेजना" },
    { word: "Sense", meaning: "संवेदना / अर्थ" },
    { word: "Separate", meaning: "अलग / अलग करना" },
    { word: "Serve", meaning: "सेवा करना / परोसना" },
    { word: "Service", meaning: "सेवा" },
    { word: "Set", meaning: "सेट / रखना" },
    { word: "Seven", meaning: "सात" },
    { word: "Share", meaning: "साझा करना / हिस्सा" },
    { word: "Short", meaning: "छोटा / संक्षिप्त" },
    { word: "Show", meaning: "दिखाना / प्रदर्शन" },
    { word: "Side", meaning: "पार्श्व / किनारा" },
    { word: "Sign", meaning: "संकेत / हस्ताक्षर" },
    { word: "Simple", meaning: "सरल / आसान" },
    { word: "Since", meaning: "से / क्योंकि" },
    { word: "Sing", meaning: "गाना" },
    { word: "Single", meaning: "एकल / अकेला" },
    { word: "Sit", meaning: "बैठना" },
    { word: "Six", meaning: "छह" },
    { word: "Sleep", meaning: "सोना" },
    { word: "Slow", meaning: "धीमा / मंद" },
    { word: "Small", meaning: "छोटा" },
    { word: "Smile", meaning: "मुस्कान" },
    { word: "Snow", meaning: "बर्फ़" },
    { word: "So", meaning: "तो / इसलिए" },
    { word: "Some", meaning: "कुछ" },
    { word: "Song", meaning: "गाना" }
],
T: [
    { word: "Table", meaning: "मेज़" },
    { word: "Take", meaning: "लेना" },
    { word: "Talk", meaning: "बात करना" },
    { word: "Tall", meaning: "लंबा" },
    { word: "Task", meaning: "कार्य / काम" },
    { word: "Taste", meaning: "स्वाद / स्वाद लेना" },
    { word: "Teach", meaning: "सिखाना" },
    { word: "Team", meaning: "टीम / दल" },
    { word: "Telephone", meaning: "टेलीफोन" },
    { word: "Tell", meaning: "बताना" },
    { word: "Temperature", meaning: "तापमान" },
    { word: "Tend", meaning: "झुकाव होना / देखभाल करना" },
    { word: "Term", meaning: "अवधि / शब्द" },
    { word: "Test", meaning: "परीक्षा / परीक्षण" },
    { word: "Thank", meaning: "धन्यवाद देना" },
    { word: "That", meaning: "वह / वह चीज़" },
    { word: "The", meaning: "वह / यह (निर्दिष्ट)" },
    { word: "Their", meaning: "उनका" },
    { word: "Them", meaning: "उन्हें / उन्हें" },
    { word: "Then", meaning: "तब / फिर" },
    { word: "There", meaning: "वहाँ" },
    { word: "These", meaning: "ये" },
    { word: "They", meaning: "वे / वे लोग" },
    { word: "Thing", meaning: "चीज़ / वस्तु" },
    { word: "Think", meaning: "सोचना" },
    { word: "Third", meaning: "तीसरा" },
    { word: "This", meaning: "यह / इस" },
    { word: "Time", meaning: "समय" },
    { word: "Title", meaning: "शीर्षक" },
    { word: "Today", meaning: "आज" },
    { word: "Together", meaning: "साथ में" },
    { word: "Tomorrow", meaning: "कल" },
    { word: "Too", meaning: "भी / बहुत" },
    { word: "Tool", meaning: "उपकरण / औजार" },
    { word: "Top", meaning: "ऊपर / शीर्ष" },
    { word: "Total", meaning: "कुल / संपूर्ण" },
    { word: "Touch", meaning: "छूना / संपर्क" },
    { word: "Town", meaning: "शहर / नगर" },
    { word: "Trade", meaning: "व्यापार" },
    { word: "Train", meaning: "ट्रेन / प्रशिक्षित करना" },
    { word: "Travel", meaning: "यात्रा करना" },
    { word: "Tree", meaning: "पेड़" }

],
U: [
    { word: "Ugly", meaning: "बदसूरत" },
    { word: "Ultimate", meaning: "अंतिम / चरम" },
    { word: "Unable", meaning: "असक्षम" },
    { word: "Uncle", meaning: "चाचा / अंकल" },
    { word: "Understand", meaning: "समझना" },
    { word: "Uniform", meaning: "वर्दी" },
    { word: "Union", meaning: "संघ / एकता" },
    { word: "Unique", meaning: "अद्वितीय / अनोखा" },
    { word: "Unit", meaning: "इकाई / यूनिट" },
    { word: "Universe", meaning: "संसार / ब्रह्मांड" },
    { word: "University", meaning: "विश्वविद्यालय" },
    { word: "Unknown", meaning: "अज्ञात" },
    { word: "Unlock", meaning: "खोलना / अनलॉक करना" },
    { word: "Until", meaning: "तक" },
    { word: "Up", meaning: "ऊपर" },
    { word: "Update", meaning: "अपडेट / नवीनतम करना" },
    { word: "Upon", meaning: "पर / ऊपर" },
    { word: "Upper", meaning: "ऊपरी" },
    { word: "Upset", meaning: "परेशान / उदास" },
    { word: "Urban", meaning: "शहरी" },
    { word: "Urgent", meaning: "तत्काल / ज़रूरी" },
    { word: "Use", meaning: "उपयोग करना" },
    { word: "Useful", meaning: "उपयोगी" },
    { word: "User", meaning: "उपयोगकर्ता" },
    { word: "Usually", meaning: "आमतौर पर" },
    { word: "Utensil", meaning: "बर्तन" },
    { word: "Utility", meaning: "सुविधा / उपयोगिता" },
    { word: "Ultimate Goal", meaning: "अंतिम लक्ष्य" },
    { word: "Update System", meaning: "सिस्टम अपडेट करना" },
    { word: "Urban Area", meaning: "शहरी क्षेत्र" },
    { word: "Usefully", meaning: "उपयोगी रूप से" },
    { word: "Understandable", meaning: "समझ में आने योग्य" },
    { word: "Unite", meaning: "एकजुट करना" },
    { word: "Unusual", meaning: "असामान्य" },
    { word: "Upper Hand", meaning: "सर्वोच्च स्थिति" },
    { word: "Urgently", meaning: "तत्काल" },
    { word: "Uplift", meaning: "उत्थान / उठाना" },
    { word: "Undertake", meaning: "संभालना / करना" },
    { word: "Unlimited", meaning: "असीमित" },
    { word: "Usefulness", meaning: "उपयोगिता" },
    { word: "Upgrade", meaning: "अपग्रेड / सुधारना" }
],
V: [
    { word: "Vacation", meaning: "छुट्टी / अवकाश" },
    { word: "Value", meaning: "मूल्य / महत्व" },
    { word: "Variable", meaning: "चर / परिवर्तनशील" },
    { word: "Vegetable", meaning: "सब्ज़ी" },
    { word: "Vehicle", meaning: "वाहन" },
    { word: "Version", meaning: "संस्करण / रूप" },
    { word: "Very", meaning: "बहुत / वास्तव में" },
    { word: "Visit", meaning: "भेंट / दौरा करना" },
    { word: "Voice", meaning: "आवाज़ / स्वर" },
    { word: "Volume", meaning: "आवाज / मात्रा" },
    { word: "Vote", meaning: "मतदान" },
    { word: "Vast", meaning: "विशाल / बड़ा" },
    { word: "Vegetarian", meaning: "शाकाहारी" },
    { word: "Venture", meaning: "साहसिक प्रयास / व्यवसाय" },
    { word: "Verify", meaning: "सत्यापित करना" },
    { word: "View", meaning: "दृश्य / देखना" },
    { word: "Village", meaning: "गाँव" },
    { word: "Violent", meaning: "हिंसक / ज़ोरदार" },
    { word: "Virtual", meaning: "आभासी / वास्तविक" },
    { word: "Vision", meaning: "दृष्टि / कल्पना" },
    { word: "Visit Friend", meaning: "मित्र से मिलना" },
    { word: "Vote Count", meaning: "मतगणना" },
    { word: "Value Added", meaning: "मूल्य संवर्धन" },
    { word: "Verify Identity", meaning: "पहचान सत्यापित करना" },
    { word: "Vocal", meaning: "स्वर / मुखर" },
    { word: "Volunteer", meaning: "स्वयंसेवक" },
    { word: "Victory", meaning: "जीत / विजय" },
    { word: "Valid", meaning: "वैध / मान्य" },
    { word: "Vanish", meaning: "गायब होना" },
    { word: "Vehicle Part", meaning: "वाहन का हिस्सा" },
    { word: "Voice Message", meaning: "आवाज़ संदेश" },
    { word: "Visit Place", meaning: "स्थान की यात्रा करना" },
    { word: "Visual", meaning: "दृश्य / दृश्यात्मक" },
    { word: "Vibrant", meaning: "जीवंत / जीवधार" },
    { word: "Volunteer Work", meaning: "स्वयंसेवा कार्य" },
    { word: "Vary", meaning: "भिन्न होना / बदलना" },
    { word: "Vegetable Market", meaning: "सब्ज़ी बाजार" },
    { word: "Vow", meaning: "प्रतिज्ञा / वचन" },
    { word: "Visit Regularly", meaning: "नियमित रूप से मिलना" },
    { word: "Vigilant", meaning: "सतर्क" },
    { word: "Vocalist", meaning: "गायक / गायिका" }
],
W: [
    { word: "Wait", meaning: "इंतज़ार करना" },
    { word: "Wake", meaning: "जागना" },
    { word: "Walk", meaning: "चलना" },
    { word: "Wall", meaning: "दीवार" },
    { word: "Want", meaning: "चाहना" },
    { word: "War", meaning: "युद्ध" },
    { word: "Warm", meaning: "गर्म / तात्त्विक" },
    { word: "Wash", meaning: "धोना" },
    { word: "Watch", meaning: "घड़ी / देखना" },
    { word: "Water", meaning: "पानी" },
    { word: "Way", meaning: "रास्ता / तरीका" },
    { word: "We", meaning: "हम" },
    { word: "Weak", meaning: "कमज़ोर" },
    { word: "Wealth", meaning: "धन / संपत्ति" },
    { word: "Wear", meaning: "पहनना" },
    { word: "Weather", meaning: "मौसम" },
    { word: "Web", meaning: "जाल / वेब" },
    { word: "Wedding", meaning: "शादी" },
    { word: "Week", meaning: "सप्ताह" },
    { word: "Welcome", meaning: "स्वागत" },
    { word: "Well", meaning: "अच्छा / कुशल" },
    { word: "West", meaning: "पश्चिम" },
    { word: "Wet", meaning: "गीला" },
    { word: "What", meaning: "क्या" },
    { word: "When", meaning: "कब" },
    { word: "Where", meaning: "कहाँ" },
    { word: "Which", meaning: "कौन सा" },
    { word: "While", meaning: "जब / जबकि" },
    { word: "White", meaning: "सफ़ेद" },
    { word: "Who", meaning: "कौन" },
    { word: "Whole", meaning: "पूरा" },
    { word: "Why", meaning: "क्यों" },
    { word: "Wide", meaning: "चौड़ा / विस्तृत" },
    { word: "Wife", meaning: "पत्नी" },
    { word: "Wild", meaning: "जंगली" },
    { word: "Win", meaning: "जीतना" },
    { word: "Wind", meaning: "हवा / घुमाना" },
    { word: "Window", meaning: "खिड़की" },
    { word: "Wine", meaning: "शराब / वाइन" },
    { word: "Winter", meaning: "सर्दी" },
    { word: "Wise", meaning: "समझदार" }
],
X: [
    { word: "X-ray", meaning: "एक्स-रे / विकिरण" },
    { word: "Xylophone", meaning: "जायलोफोन (संगीत वाद्य)" },
    { word: "Xenon", meaning: "ज़ेनॉन (रासायनिक तत्व)" },
    { word: "Xerox", meaning: "फोटो कॉपी करना" },
    { word: "Xerography", meaning: "सूखी प्रतिलिपि बनाना" },
    { word: "Xylograph", meaning: "लकड़ी पर चित्र बनाना" },
    { word: "Xylography", meaning: "लकड़ी छपाई कला" },
    { word: "Xenophobia", meaning: "पराई से डर / घृणा" },
    { word: "Xylophonist", meaning: "जायलोफोन बजाने वाला" },
    { word: "X-axis", meaning: "एक्स-अक्ष (रेखा)" },
    { word: "Xerarch", meaning: "सूखे पर्यावरण का पौधा" },
    { word: "Xenial", meaning: "अतिथि सत्कार वाला" },
    { word: "Xebec", meaning: "एक प्रकार की नाव" },
    { word: "Xylocarp", meaning: "कठोर फल / लकड़ी जैसा फल" },
    { word: "Xylotomy", meaning: "लकड़ी का अध्ययन / विश्लेषण" },
    { word: "Xerophilous", meaning: "सूखे वातावरण में उगने वाला" },
    { word: "Xyloid", meaning: "लकड़ी जैसा" },
    { word: "Xanthic", meaning: "पीला रंग वाला" },
    { word: "Xerothermic", meaning: "सूखा और गर्म" },
    { word: "Xylenol", meaning: "एक रासायनिक यौगिक" },
    { word: "Xenogeneic", meaning: "विदेशी उत्पत्ति का" },
    { word: "Xenolithic", meaning: "विदेशी चट्टान का टुकड़ा" },
    { word: "Xylenes", meaning: "रासायनिक पदार्थ / सॉल्वेंट" },
    { word: "Xenograft", meaning: "विदेशी ऊतक प्रत्यारोपण" },
    { word: "X-ray Vision", meaning: "एक्स-रे दृष्टि" },
    { word: "Xylocaine", meaning: "एक लोकल एनेस्थेटिक" },
    { word: "Xenial Relation", meaning: "अतिथि सत्कार संबंध" },
    { word: "Xylophonist Performance", meaning: "जायलोफोन प्रदर्शन" },
    { word: "X-axis Movement", meaning: "एक्स-अक्ष पर गति" },
    { word: "Xenophile", meaning: "विदेशी संस्कृति प्रेमी" },
    { word: "X-ray Machine", meaning: "एक्स-रे मशीन" },
    { word: "Xanthophyll", meaning: "पत्ती का पीला रंगक" },
    { word: "Xeriscape", meaning: "सूखी मिट्टी में बागवानी" },
    { word: "Xenium", meaning: "उपहार / देन" },
    { word: "Xylograph Print", meaning: "लकड़ी की छपाई" },
    { word: "Xeroderma", meaning: "त्वचा की सूखापन बीमारी" },
    { word: "Xenotransplant", meaning: "विदेशी अंग प्रत्यारोपण" },
    { word: "Xylography Art", meaning: "लकड़ी छपाई कला" },
    { word: "X-ray Scan", meaning: "एक्स-रे स्कैन" },
    { word: "Xylocaine Injection", meaning: "लोकल एनेस्थेटिक इंजेक्शन" },
    { word: "Xerophytic Plant", meaning: "सूखा पौधा" }
],
Y: [
    { word: "Yacht", meaning: "याट / नौका" },
    { word: "Yard", meaning: "यार्ड / आंगन" },
    { word: "Yawn", meaning: "जंभाई लेना" },
    { word: "Year", meaning: "साल / वर्ष" },
    { word: "Yellow", meaning: "पीला" },
    { word: "Yes", meaning: "हाँ" },
    { word: "Yesterday", meaning: "कल" },
    { word: "Yet", meaning: "अभी तक / फिर भी" },
    { word: "Yield", meaning: "उत्पादन / देना" },
    { word: "Young", meaning: "युवा / जवान" },
    { word: "Your", meaning: "आपका / तुम्हारा" },
    { word: "Yours", meaning: "आपका / तुम्हारा" },
    { word: "Yourself", meaning: "खुद / स्वयं" },
    { word: "Youth", meaning: "युवा / युवावस्था" },
    { word: "Yearly", meaning: "वार्षिक" },
    { word: "Yell", meaning: "चिल्लाना" },
    { word: "Yoga", meaning: "योग" },
    { word: "Yolk", meaning: "अंडे की ज़र्दी" },
    { word: "Yummy", meaning: "स्वादिष्ट" },
    { word: "Yardstick", meaning: "मानक / पैमाना" },
    { word: "Yawning", meaning: "जंभाई लेना" },
    { word: "Year-end", meaning: "वर्ष का अंत" },
    { word: "Yes-man", meaning: "आज्ञाकारी व्यक्ति" },
    { word: "Yesterday’s News", meaning: "कल की खबर" },
    { word: "Youthful", meaning: "युवावस्था जैसा" },
    { word: "Yesteryear", meaning: "पिछला साल / पुराने समय" },
    { word: "Yielding", meaning: "उत्पादक / लचीला" },
    { word: "Yellowish", meaning: "पीला सा" },
    { word: "Yodel", meaning: "गाना / योडल" },
    { word: "Yoke", meaning: "जुड़न / हल का जोड़" },
    { word: "Yard Work", meaning: "आंगन का काम" },
    { word: "Yeast", meaning: "खमीर" },
    { word: "Yap", meaning: "भौंकना / बोलना" },
    { word: "Youngster", meaning: "युवा / बच्चा" },
    { word: "Yield Strength", meaning: "उत्पादन क्षमता" },
    { word: "Yarn", meaning: "सुई / ऊन" },
    { word: "Yard Sale", meaning: "घर का सामान बेचना" },
    { word: "Yoga Class", meaning: "योग कक्षा" },
    { word: "Younger", meaning: "छोटा / युवा" },
    { word: "Your Honor", meaning: "मान्यवर" },
    { word: "Your Opinion", meaning: "आपकी राय" }
],
Z: [
    { word: "Zebra", meaning: "ज़ेब्रा / धारियों वाला घोड़ा" },
    { word: "Zero", meaning: "शून्य" },
    { word: "Zone", meaning: "क्षेत्र / ज़ोन" },
    { word: "Zoom", meaning: "ज़ूम करना / बढ़ाना" },
    { word: "Zodiac", meaning: "राशिचक्र" },
    { word: "Zoology", meaning: "पशु विज्ञान" },
    { word: "Zany", meaning: "मज़ाकिया / विचित्र" },
    { word: "Zeal", meaning: "उत्साह / जोश" },
    { word: "Zealous", meaning: "उत्साही / मेहनती" },
    { word: "Zenith", meaning: "शिखर / चरम" },
    { word: "Zip", meaning: "ज़िप / जल्दी से करना" },
    { word: "Zigzag", meaning: "झींगझींग / टेढ़ा" },
    { word: "Zinc", meaning: "जस्ता" },
    { word: "Zombie", meaning: "ज़ॉम्बी / मृत व्यक्ति" },
    { word: "Zone Out", meaning: "ध्यान खो देना" },
    { word: "Zoom Meeting", meaning: "ज़ूम बैठक" },
    { word: "Zoologist", meaning: "पशु वैज्ञानिक" },
    { word: "Zero Tolerance", meaning: "शून्य सहनशीलता" },
    { word: "Zest", meaning: "उत्साह / आनंद" },
    { word: "Zipper", meaning: "ज़िपर / फास्टनर" },
    { word: "Zonal", meaning: "क्षेत्रीय / ज़ोन का" },
    { word: "Zephyr", meaning: "हल्की हवा / मंद हवा" },
    { word: "Zombie Walk", meaning: "ज़ॉम्बी चाल" },
    { word: "Zoological Park", meaning: "चिड़ियाघर" },
    { word: "Zero Hour", meaning: "निर्धारित समय / ज़ीरो ऑवर" },
    { word: "Zinc Plate", meaning: "जस्ता प्लेट" },
    { word: "Zoology Study", meaning: "पशु विज्ञान अध्ययन" },
    { word: "Zigzag Path", meaning: "टेढ़ा रास्ता" },
    { word: "Zoom Lens", meaning: "ज़ूम लेंस" },
    { word: "Zealous Worker", meaning: "उत्साही कर्मचारी" },
    { word: "Zoological Survey", meaning: "पशु सर्वेक्षण" },
    { word: "Zodiac Sign", meaning: "राशि चिन्ह" },
    { word: "Zero Point", meaning: "शून्य बिंदु" },
    { word: "Zany Idea", meaning: "मज़ाकिया विचार" },
    { word: "Zookeeper", meaning: "चिड़ियाघर का कर्मचारी" },
    { word: "Zoological Garden", meaning: "पशु उद्यान" },
    { word: "Zonal Office", meaning: "क्षेत्रीय कार्यालय" },
    { word: "Zip File", meaning: "ज़िप फ़ाइल" },
    { word: "Zoom In", meaning: "ज़ूम इन करना" },
    { word: "Zoom Out", meaning: "ज़ूम आउट करना" },
    { word: "Zebra Crossing", meaning: "ज़ेब्रा क्रॉसिंग / पैदल यात्री मार्ग" }
]

};

// Display words with Hindi meanings
function showWords(letter) {
    wordsContainer.innerHTML = '';
    if(dictionary[letter]) {
        dictionary[letter].forEach(item => {
            const wordDiv = document.createElement('div');
            wordDiv.className = 'word';
            wordDiv.innerHTML = `<strong>${item.word}</strong> - ${item.meaning}`;
            wordsContainer.appendChild(wordDiv);
        });
    } else {
        wordsContainer.textContent = 'No words available for this letter.';
    }
}
